FROM oven/bun:1

ARG DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy"
ENV DATABASE_URL=$DATABASE_URL
WORKDIR /usr/src/app

COPY . .
RUN apt-get update -y && apt-get install -y openssl

RUN bun install

RUN bun run generate:db
RUN DB_URL=$DB_URL bunx turbo build --filter=web...

EXPOSE 3000

# Start the frontend application
CMD ["bun", "start:frontend"]